CREATE DATABASE base_arc;
USE base_arc;

CREATE TABLE SYS_USER (
  ID BIGINT,
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  SALT     VARCHAR(50),
  LOCKED   BOOL
);

CREATE TABLE SYS_ROLE(
  ID BIGINT,
  ROLE_NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  AVAILABLE BOOL
);

CREATE TABLE SYS_USER_ROLE(
  SYS_USER_ID VARCHAR(255),
  SYS_ROLE_ID VARCHAR(255)
);

CREATE TABLE SYS_PERMISSION(
  ID BIGINT,
  PERMISSION_NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  AVAILABLE BOOL
);








CREATE TABLE SYS_RESOURCE(
  ID  BIGINT,
  NAME VARCHAR(255),
  TYPE VARCHAR(100),
  PRIORITY INT,
  PARENT_ID BIGINT,
  PARENT_IDS VARCHAR(255),
  PERMISSION VARCHAR(255),
  AVAILABLE  BOOL
);

CREATE TABLE SYS_ORGANIZATION(
  ID  BIGINT,
  NAME VARCHAR(255),
  PRIORITY INT,
  PARENT_ID BIGINT,
  PARENT_IDS VARCHAR(255),
  AVAILABLE  BOOL
);


CREATE TABLE SYS_DICT(
  _KEY VARCHAR(100),
  _VALUE VARCHAR(500)
);

# INSERT INTO SYS_DICT values ('LOGIN_ER_01','用户名为空');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_02','密码为空');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_03','验证码为空');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_04','验证码不匹配');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_05','用户名密码错误');



# INSERT INTO SYS_USER(ID,USERNAME,PASSWORD,SALT,LOCKED) VALUES (123456,'admin','df49ec48e56522d11151fb9ecd683aef','123',FALSE)


############################### START ################################
CREATE TABLE SYS_EMPLOYEE (
  _ID VARCHAR(32) PRIMARY KEY,
  _NAME VARCHAR(100),
  _EMAIL VARCHAR(100),
  _TEL VARCHAR(20),
  _NO VARCHAR(20),
  _ICON_ID VARCHAR(200),

  _ACCOUNT VARCHAR(50),
  _PASSWORD VARCHAR(255),
  _SALT VARCHAR(20),
  _STATUS INT
);

#INSERT INTO SYS_EMPLOYEE VALUES ('CD000001','王五','505211778@qq.com','15281061543','CD00001',NULL,'admin','df49ec48e56522d11151fb9ecd683aef','123',0);

CREATE TABLE SYS_DEPARTMENT (
  _ID VARCHAR(32) PRIMARY KEY,
  _NAME VARCHAR(100)
);

CREATE TABLE SYS_EMP_DEPT (
  _EMP_ID VARCHAR(32),
  FOREIGN KEY(_EMP_ID) REFERENCES SYS_EMPLOYEE(_ID)  ,
  _DEPT_ID VARCHAR(32),
  FOREIGN KEY (_DEPT_ID) REFERENCES SYS_EMPLOYEE(_ID)
);



CREATE TABLE SYS_MENU(
  _ID VARCHAR(32) PRIMARY KEY ,
  _NAME VARCHAR(100),
  _PATH VARCHAR(200),
  _PARENT_ID VARCHAR(32),
  _ORDER INT,
  _TYPE INT,
  UNIQUE KEY MENU_URI (_PATH)
);

# INSERT INTO SYS_MENU VALUES ('MENU_01','首页','dashboard',NULL,1,0);
# INSERT INTO SYS_MENU VALUES ('MENU_02','企业员工权限管理','emplmanage',NULL,2,1);
# INSERT INTO SYS_MENU VALUES ('MENU_03','企业员工管理','emplmanage/employee','MENU_02',3,0);
# INSERT INTO SYS_MENU VALUES ('MENU_04','企业权限管理','emplmanage/permission','MENU_02',4,0);






























