CREATE DATABASE base_arc;
USE base_arc;

CREATE TABLE SYS_USER (
  ID BIGINT,
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  SALT     VARCHAR(50),
  LOCKED   BOOL
);

CREATE TABLE SYS_ROLE(
  ID BIGINT,
  ROLE_NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  AVAILABLE BOOL
);

CREATE TABLE SYS_USER_ROLE(
  SYS_USER_ID VARCHAR(255),
  SYS_ROLE_ID VARCHAR(255)
);

CREATE TABLE SYS_PERMISSION(
  ID BIGINT,
  PERMISSION_NAME VARCHAR(255),
  DESCRIPTION VARCHAR(2000),
  AVAILABLE BOOL
);








CREATE TABLE SYS_RESOURCE(
  ID  BIGINT,
  NAME VARCHAR(255),
  TYPE VARCHAR(100),
  PRIORITY INT,
  PARENT_ID BIGINT,
  PARENT_IDS VARCHAR(255),
  PERMISSION VARCHAR(255),
  AVAILABLE  BOOL
);

CREATE TABLE SYS_ORGANIZATION(
  ID  BIGINT,
  NAME VARCHAR(255),
  PRIORITY INT,
  PARENT_ID BIGINT,
  PARENT_IDS VARCHAR(255),
  AVAILABLE  BOOL
);


CREATE TABLE SYS_DICT(
  _KEY VARCHAR(100),
  _VALUE VARCHAR(500)
);

# INSERT INTO SYS_DICT values ('LOGIN_ER_01','用户名为空');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_02','密码为空');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_03','验证码为空');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_04','验证码不匹配');
#
# INSERT INTO SYS_DICT values ('LOGIN_ER_05','用户名密码错误');



# INSERT INTO SYS_USER(ID,USERNAME,PASSWORD,SALT,LOCKED) VALUES (123456,'ZHAGNSAN','ZHANGSAN','ZHANG123',FALSE)